---
os: linux

jobs:
  include:
    - name: Xenial xsltproc
      dist: xenial
      language: shell
      addons:
        apt:
          packages:
            - xsltproc
            - libxml2-utils
      script: ./test.sh

    - name: Bionic xsltproc
      dist: bionic
      language: shell
      addons:
        apt:
          packages:
            - xsltproc
            - libxml2-utils
      script: ./test.sh

    - name: Firefox
      dist: bionic
      language: node_js
      node_js: lts/*
      addons:
        firefox: latest
      install: npm install karma karma-firefox-launcher karma-mocha karma-chai mocha chai
      script: npx karma start --single-run --browsers FirefoxHeadless karma.conf.js

    - name: Chrome
      dist: bionic
      language: node_js
      node_js: lts/*
      addons:
        chrome: stable
      install: npm install karma karma-chrome-launcher karma-mocha karma-chai mocha chai
      script: npx karma start --single-run --browsers ChromeHeadless karma.conf.js
